// GENERATED by @temporal-agent-harness/codegen from examples.agent_dag.workflow:DagBuilderAgentWorkflow. Do not edit.

/**
 * A flow script to run: Python that calls `run_agent` to start step agents, in sequence
 * or in parallel, and returns what the last of them produced.
 */
export interface RunFlow {
  script: string;
}
/**
 * Free-form natural-language text from the user (the input to a plain chat handler).
 */
export interface TextMessage {
  text: string;
}
/**
 * A free-form natural-language reply (the output of a plain chat handler).
 */
export interface TextReply {
  text: string;
}

/** The `DagBuilderAgent` agent's init data, handlers (message in, reply out) and observable
 *  state. */
export interface DagBuilderAgent {
  initData: null;
  handlers: {
    /**
     * Run a flow script. Each `run_agent` call starts a step agent as a subagent; the reply is
     * what the script printed and returned.
     */
    execute: { input: RunFlow; output: TextReply };
    /**
     * Describe the flow you want, or a change to the current one. The agent writes it into
     * your editor, one edit at a time.
     */
    generate: { input: TextMessage; output: TextReply };
  };
  states: Record<never, never>;
}

/** Pass to `startSession` to start a `DagBuilderAgent` session. */
export const DagBuilderAgent: { readonly workflowType: "DagBuilderAgent"; readonly schema?: DagBuilderAgent } = {
  workflowType: "DagBuilderAgent"
};
