// GENERATED by @temporal-agent-harness/codegen from examples.agent_dag.step_agent:DagStepAgentWorkflow. Do not edit.

/**
 * The step agent's spec, published so a client can label the step it is watching.
 */
export interface StepProfile {
  name: string;
  instructions: string;
  tools: string[];
  model: string;
}
/**
 * Everything that makes one step agent what it is. A flow script sets it per step.
 */
export interface StepSpec {
  /**
   * A short name for the step.
   *
   * @minLength 1
   * @maxLength 60
   */
  name: string;
  /**
   * The step agent's system prompt.
   */
  instructions: string;
  /**
   * The tools this step agent may call.
   */
  tools?: ("search_flights" | "search_hotels" | "book_flight" | "book_hotel" | "get_trip_summary" | "get_weather")[];
  model?: "gpt-6-luna" | "gpt-6.1-sol";
}
/**
 * Free-form natural-language text from the user (the input to a plain chat handler).
 */
export interface TextMessage {
  text: string;
}
/**
 * A free-form natural-language reply (the output of a plain chat handler).
 */
export interface TextReply {
  text: string;
}

/** The `DagStepAgent` agent's init data, handlers (message in, reply out) and observable
 *  state. */
export interface DagStepAgent {
  initData: { data: StepSpec; required: true };
  handlers: {
    /** Give this step its task. It works on it with its tools and replies with the result. */
    ask: { input: TextMessage; output: TextReply };
  };
  states: {
    profile: StepProfile;
  };
}

/** Pass to `startSession` to start a `DagStepAgent` session. */
export const DagStepAgent: { readonly workflowType: "DagStepAgent"; readonly schema?: DagStepAgent } = {
  workflowType: "DagStepAgent"
};
