# Generated by nexus-rpc-gen. DO NOT EDIT!

from __future__ import annotations

from pydantic import BaseModel
from typing import Dict, Any, List, Optional
from nexusrpc import service, Operation


class HandlerElement(BaseModel):
    """One @agent.accepts handler an agent exposes, described tool-style (mirrors harness
    AcceptedFunction).
    """
    description: str
    """Handler docstring describing when and how to use it."""

    name: str
    """Handler name - the value to pass as msgType in sendAgentMessage."""

    output: Dict[str, Any]
    """JSON Schema for the handler's return model."""

    parameters: Dict[str, Any]
    """JSON Schema for the handler's input model."""


class RegisterAgentInput(BaseModel):
    agent_key: str
    """Stable key other agents discover this agent by."""

    endpoint: str
    """This agent's own AgentService Nexus endpoint."""

    handlers: List[HandlerElement]
    """This agent's capability, supplied at registration time."""

    description: Optional[str] = None
    """Human-readable summary shown to a discovering parent."""


class RegisterAgentOutput(BaseModel):
    registered: bool


class DeregisterAgentInput(BaseModel):
    agent_key: str


class DeregisterAgentOutput(BaseModel):
    deregistered: bool


class DiscoverAgentsInput(BaseModel):
    pass


class AgentElement(BaseModel):
    """One directory entry, as returned by discover_agents."""

    agent_key: str
    endpoint: str
    handlers: List[HandlerElement]
    description: Optional[str] = None


class DiscoverAgentsOutput(BaseModel):
    agents: List[AgentElement]


@service
class AgentRegistryService:
    """Directory service agents register their Nexus-facing capability with, and parent agents
    query to discover what's available. A directory only - discovered agents are driven
    directly via their own AgentService, never through the registry.
    """
    register_agent: Operation[RegisterAgentInput, RegisterAgentOutput]
    """An agent announces itself: its key, where to reach it (its own AgentService Nexus
    endpoint), and its capability (the same AcceptedFunction list agent_interface exposes).
    """

    deregister_agent: Operation[DeregisterAgentInput, DeregisterAgentOutput]
    """Remove an agent's directory entry. Idempotent."""

    discover_agents: Operation[DiscoverAgentsInput, DiscoverAgentsOutput]
    """Return the full current directory - every registered agent's key, endpoint, description,
    and capability.
    """
