# ABOUTME: The public agent protocol surface — the workflow-stream event vocabulary, the
# signal/update/query interface an agent workflow and its clients share, and the subagent-turn
# activity contract (parent workflow ↔ harness activity, in ``subagent_interface``).
# Re-exports every protocol type so consumers import flat names from one package
# (``from harness.agent_protocol import AgentEvent, AgentMessage, ...``) without reaching into
# submodules. This package depends only on stdlib + pydantic, so it imports cleanly
# inside the Temporal workflow sandbox.

from temporal_agent_harness.harness.agent_protocol.agent_interface import (
    AGENT_ID_LENGTH,
    AGENT_INTERFACE_QUERY,
    AGENT_STATUS_QUERY,
    EXECUTE_OPERATOR_COMMAND_UPDATE,
    OPERATOR_INTERFACE_QUERY,
    PROVIDE_CALLBACK_RESULT_UPDATE,
    SEND_AGENT_MESSAGE_UPDATE,
    SET_ENABLED_MCP_SERVERS_UPDATE,
    TOOL_APPROVAL_UPDATE,
    AcceptedFunction,
    AgentConfig,
    AgentId,
    AgentMessage,
    AgentStatus,
    CallbackResult,
    CallbackResultAck,
    OperatorCommand,
    OperatorCommandArgument,
    OperatorCommandRequest,
    OperatorCommandResult,
    PendingApproval,
    PendingCallback,
    PendingTurn,
    SlashCommand,
    SubagentInfo,
    TextMessage,
    TextReply,
    ToolApprovalContext,
    ToolApprovalDecision,
    ToolApprovalPolicy,
    ToolApprovalResult,
    AgentMessageReply,
)
from temporal_agent_harness.harness.agent_protocol.events import (
    TURN_EVENTS_TOPIC,
    AgentError,
    AgentEvent,
    AgentEventType,
    AgentReply,
    AgentStreamItem,
    CallbackRequested,
    CallbackResolved,
    EventTypeT,
    MessageQueued,
    ModelInteractionEnded,
    ModelInteractionStarted,
    OperatorCommandCompleted,
    OperatorCommandEvent,
    OperatorCommandFailed,
    OperatorCommandStarted,
    ReplyDelta,
    StreamEvent,
    SubagentMessageSent,
    SubagentReplyReceived,
    SubagentStarted,
    SubagentStopped,
    SubagentStreamUnavailable,
    TextAnnotationDelta,
    ThoughtSummaryDelta,
    TokenUsage,
    ToolApprovalRequested,
    ToolApprovalResolved,
    ToolEndEvent,
    ToolErrorEvent,
    ToolEvent,
    ToolProgressDelta,
    ToolRequested,
    ToolStartEvent,
    TurnEnded,
    TurnStarted,
)
from temporal_agent_harness.harness.agent_protocol.subagent_interface import (
    DEFAULT_SUBAGENT_HEARTBEAT_INTERVAL,
    DEFAULT_SUBAGENT_HEARTBEAT_TIMEOUT,
    DEFAULT_SUBAGENT_START_TO_CLOSE_TIMEOUT,
    RUN_SUBAGENT_TURN_ACTIVITY,
    RunSubagentTurnInput,
    SubagentTurnResult,
)

__all__ = [
    # Signal/update/query interface
    "AGENT_ID_LENGTH",
    "AGENT_INTERFACE_QUERY",
    "AGENT_STATUS_QUERY",
    "EXECUTE_OPERATOR_COMMAND_UPDATE",
    "OPERATOR_INTERFACE_QUERY",
    "PROVIDE_CALLBACK_RESULT_UPDATE",
    "SEND_AGENT_MESSAGE_UPDATE",
    "SET_ENABLED_MCP_SERVERS_UPDATE",
    "TOOL_APPROVAL_UPDATE",
    "AcceptedFunction",
    "AgentConfig",
    "AgentId",
    "AgentMessage",
    "AgentStatus",
    "CallbackResult",
    "CallbackResultAck",
    "OperatorCommand",
    "OperatorCommandArgument",
    "OperatorCommandRequest",
    "OperatorCommandResult",
    "PendingApproval",
    "PendingCallback",
    "PendingTurn",
    "SlashCommand",
    "SubagentInfo",
    "TextMessage",
    "TextReply",
    "ToolApprovalContext",
    "ToolApprovalDecision",
    "ToolApprovalPolicy",
    "ToolApprovalResult",
    "AgentMessageReply",
    # Stream-event vocabulary
    "TURN_EVENTS_TOPIC",
    "AgentEventType",
    "EventTypeT",
    "StreamEvent",
    "MessageQueued",
    "TurnStarted",
    "TurnEnded",
    "OperatorCommandEvent",
    "OperatorCommandStarted",
    "OperatorCommandCompleted",
    "OperatorCommandFailed",
    "ModelInteractionStarted",
    "ModelInteractionEnded",
    "ToolEvent",
    "ToolRequested",
    "ToolApprovalRequested",
    "ToolApprovalResolved",
    "ToolStartEvent",
    "ToolEndEvent",
    "ToolProgressDelta",
    "ToolErrorEvent",
    "CallbackRequested",
    "CallbackResolved",
    "SubagentStarted",
    "SubagentStopped",
    "SubagentMessageSent",
    "SubagentReplyReceived",
    "SubagentStreamUnavailable",
    "ReplyDelta",
    "ThoughtSummaryDelta",
    "TextAnnotationDelta",
    "TokenUsage",
    "AgentReply",
    "AgentError",
    "AgentStreamItem",
    "AgentEvent",
    # Subagent-turn activity contract (parent workflow ↔ harness activity)
    "RUN_SUBAGENT_TURN_ACTIVITY",
    "DEFAULT_SUBAGENT_HEARTBEAT_INTERVAL",
    "DEFAULT_SUBAGENT_HEARTBEAT_TIMEOUT",
    "DEFAULT_SUBAGENT_START_TO_CLOSE_TIMEOUT",
    "RunSubagentTurnInput",
    "SubagentTurnResult",
]
