"""``cedar_schema`` — the Cedar schema for the tool calls ``cedar_evaluator`` sends.

The Cedar verifier refuses to start on policies that don't match its schema, and a policy can
only name an action the schema declares. Writing the schema by hand means keeping it in step
with every tool's arguments, every Code Mode tool's host functions and the classifier's
questions; when it drifts, calls fail closed in ways that are hard to read (an undeclared
action is denied, a ``has`` check is never true). This generates it from the same tools the
agent runs.

Every attribute a tool call may lack is optional, so policies must check with ``has`` and a
missing value fails closed. Floats, nulls and maps without fixed keys are left out, with a
comment saying so: the verifier drops floats and nulls, and a Cedar record needs its keys
declared.

Hand the output to the verifier as ``CEDAR_SCHEMA_FILE``, next to the policies.
"""

from __future__ import annotations

import inspect
import json
import re
from collections.abc import Awaitable, Callable, Sequence
from typing import Any

from pydantic import create_model

from temporal_agent_harness.harness.code_mode.stubs import resolve_hints
from temporal_agent_harness.harness.jev_approvals.classifier import ScriptFeature

_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

_HEADER = """\
// Generated by temporal_agent_harness.harness.cedar_approvals.cedar_schema. Regenerate it when
// the agent's tools change; don't edit it by hand.
//
// Every tool call is one authorization request:
//   principal: Worker::"<subject>", the agent (its workflow type, unless configured)
//   action:    Action::"<prefix>/<tool name>"
//   resource:  TaskQueue::"<task queue>", the agent's task queue
//   context:   the workflow ID and the call's single parameter, arg0

entity Worker = {
  namespace: String,
};

entity TaskQueue = {
  name: String,
  namespace: String,
};
"""

_HOST_FUNCTION_USE = (
    "{ call_sites: Long, in_loop: Bool, concurrent: Bool, indirect: Bool }"
)


def cedar_schema(
    tools: Sequence[Callable[..., Awaitable[Any]]],
    *,
    action_prefix: str,
    script_features: Sequence[ScriptFeature] = (),
) -> str:
    """The Cedar schema declaring one action per tool in ``tools``.

    Args:
        tools: The harness tools the agent gates through ``cedar_evaluator``: tools made with
            ``@agent.tool_defn`` / ``@agent.activity_tool_defn``, and ``code_mode_tool`` tools.
            Include the tools a Code Mode tool exposes, since each host call is judged on its
            own too.
        action_prefix: The evaluator's ``action_prefix``. Actions are
            ``<action_prefix>/<tool name>``.
        script_features: The classifier's features, declared as ``classification`` on every
            Code Mode action. Leave empty when the evaluator has no classifier.
    """
    sections = [_HEADER]
    for tool in tools:
        name = getattr(tool, "__name__", None)
        if not (
            name
            and (
                getattr(tool, "__agent_tool__", False)
                or getattr(tool, "__agent_activity_tool__", False)
            )
        ):
            raise TypeError(f"{tool!r} is not a harness tool")
        host_functions = getattr(tool, "__code_mode_host_functions__", None)
        lines = (
            _script_data(host_functions, script_features)
            if host_functions is not None
            else _arguments_data(tool)
        )
        sections.append(_action(f"{action_prefix}/{name}", lines))
    return "\n".join(sections)


def _action(name: str, data: list[str]) -> str:
    body = "\n".join(f"          {line}" for line in data)
    return f"""\
action {json.dumps(name)} appliesTo {{
  principal: Worker,
  resource: TaskQueue,
  context: {{
    workflowId: String,
    parameterCount: Long,
    parameters: {{
      arg0?: {{
        type: String,
        data: {{
{body}
        }},
      }},
    }},
  }},
}};
"""


def _script_data(
    host_functions: frozenset[str], features: Sequence[ScriptFeature]
) -> list[str]:
    lines = [
        "calls?: Set<String>,",
        "uses?: {",
        *(f"  {_attr(fn)}?: {_HOST_FUNCTION_USE}," for fn in sorted(host_functions)),
        "},",
        "has_while_loop?: Bool,",
        "dynamic_code?: Bool,",
    ]
    if features:
        lines += [
            "classification?: {",
            *(f"  {_attr(feature.key)}?: Long," for feature in features),
            "},",
        ]
    return lines


def _arguments_data(tool: Callable[..., Any]) -> list[str]:
    """Record attributes for the tool's model-facing arguments, from their JSON schema."""
    hints = resolve_hints(tool)
    fields: dict[str, Any] = {}
    for param in inspect.signature(tool).parameters.values():
        annotation = hints.get(param.name, param.annotation)
        if annotation is inspect.Parameter.empty or isinstance(annotation, str):
            annotation = Any
        default = ... if param.default is inspect.Parameter.empty else param.default
        fields[param.name] = (annotation, default)
    schema = create_model(f"{tool.__name__}_arguments", **fields).model_json_schema()
    return _record_lines(schema, schema.get("$defs", {}), frozenset())


def _record_lines(
    schema: dict[str, Any], defs: dict[str, Any], seen: frozenset[str]
) -> list[str]:
    lines: list[str] = []
    for prop, prop_schema in (schema.get("properties") or {}).items():
        rendered = _cedar_type(prop_schema, defs, seen)
        if rendered is None:
            lines.append(f"// {prop}: {_describe(prop_schema, defs)}, which Cedar can't see")
        elif rendered == "{":
            record, refs = _resolve(prop_schema, defs)
            inner = _record_lines(record, defs, seen | refs)
            lines += [f"{_attr(prop)}?: {{", *(f"  {line}" for line in inner), "},"]
        else:
            lines.append(f"{_attr(prop)}?: {rendered},")
    return lines


def _resolve(
    schema: dict[str, Any], defs: dict[str, Any]
) -> tuple[dict[str, Any], frozenset[str]]:
    """``schema`` with ``$ref``s, a single ``allOf`` and a nullable ``anyOf`` unwrapped, and the
    names of the definitions it passed through."""
    refs: set[str] = set()
    while True:
        if "$ref" in schema:
            name = schema["$ref"].rsplit("/", 1)[-1]
            if name in refs:
                return schema, frozenset(refs)
            refs.add(name)
            schema = defs[name]
        elif len(schema.get("allOf", ())) == 1:
            schema = schema["allOf"][0]
        elif "anyOf" in schema:
            options = [o for o in schema["anyOf"] if o.get("type") != "null"]
            if len(options) != 1:
                return schema, frozenset(refs)
            schema = options[0]
        else:
            return schema, frozenset(refs)


def _cedar_type(schema: dict[str, Any], defs: dict[str, Any], seen: frozenset[str]) -> str | None:
    """The Cedar type for a JSON schema, ``"{"`` for a record, or ``None`` if Cedar can't see it."""
    schema, refs = _resolve(schema, defs)
    if refs & seen or "$ref" in schema:
        return None  # a model that contains itself
    seen = seen | refs
    if "anyOf" in schema:
        kinds = {_cedar_type(option, defs, seen) for option in schema["anyOf"]} - {None}
        return kinds.pop() if len(kinds) == 1 and "{" not in kinds else None
    if "enum" in schema or "const" in schema:
        values = schema.get("enum", [schema.get("const")])
        for kind, cedar in ((str, "String"), (bool, "Bool"), (int, "Long")):
            if all(isinstance(v, kind) for v in values):
                return cedar
        return None
    kind = schema.get("type")
    if kind == "string":
        return "String"
    if kind == "integer":
        return "Long"
    if kind == "boolean":
        return "Bool"
    if kind == "array":
        items = _cedar_type(schema.get("items") or {}, defs, seen)
        return f"Set<{items}>" if items is not None and items != "{" else None
    if kind == "object" and schema.get("properties"):
        return "{"
    return None


def _describe(schema: dict[str, Any], defs: dict[str, Any]) -> str:
    kind = _resolve(schema, defs)[0].get("type")
    return {"number": "a float", "object": "a map", "null": "a null"}.get(
        kind or "", "a value of no single type"
    )


def _attr(name: str) -> str:
    return name if _IDENTIFIER.match(name) else json.dumps(name)
