# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal_agent_harness/harness/cedar_approvals/toolpolicy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?temporal_agent_harness/harness/cedar_approvals/toolpolicy.proto\x12(temporal_untrusted_workers.toolpolicy.v1\":\n\x17VerifyToolCallsResponse\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\tb\x06proto3')



_VERIFYTOOLCALLSRESPONSE = DESCRIPTOR.message_types_by_name['VerifyToolCallsResponse']
VerifyToolCallsResponse = _reflection.GeneratedProtocolMessageType('VerifyToolCallsResponse', (_message.Message,), {
  'DESCRIPTOR' : _VERIFYTOOLCALLSRESPONSE,
  '__module__' : 'temporal_agent_harness.harness.cedar_approvals.toolpolicy_pb2'
  # @@protoc_insertion_point(class_scope:temporal_untrusted_workers.toolpolicy.v1.VerifyToolCallsResponse)
  })
_sym_db.RegisterMessage(VerifyToolCallsResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VERIFYTOOLCALLSRESPONSE._serialized_start=109
  _VERIFYTOOLCALLSRESPONSE._serialized_end=167
# @@protoc_insertion_point(module_scope)
