// GENERATED by @temporal-agent-harness/codegen from the harness event protocol
// (`temporal-agent-harness schema --protocol`). Do not edit.

/**
 * What an auto mode evaluator decided about one gated tool call.
 *
 * Three-valued on purpose. An evaluator is not merely an "extra yes": it is a
 * *decision-maker*, and the interesting case — an AI auto-approver judging a call it has
 * never seen before — needs to be able to say "no" as loudly as it says "yes", and to
 * abstain when it is not sure enough to say either.
 *
 *   * `APPROVE` — dispatch the call now, with no human gate.
 *   * `DENY` — the call ends here. It never executes; the tool raises
 *     `temporal_agent_harness.harness.agent_workflow.ToolApprovalDenied`, which
 *     the agent loop surfaces to the model as an error result, so the turn continues.
 *   * `ESCALATE` — abstain. The call stays PENDING and waits for a human decision on
 *     the `tool_approval` update, exactly as if auto mode were off.
 *
 * `ESCALATE` — not `DENY` — is the safe answer to "I don't know": denying on
 * uncertainty trains operators to disable the guardrail, while escalating puts the call
 * in front of the person who can actually judge it.
 */
export type AutoApprovalVerdict = "approve" | "deny" | "escalate";
/**
 * What an admitted message actually did to the agent's turn — the OUTCOME half of
 * `MidTurn`'s declaration.
 *
 * `MidTurn` is what the handler's author declared should happen mid-turn; this is what
 * happened to one particular message, which also depends on whether the agent was busy at
 * all. An idle agent gives every mode the same answer (`OPENED`), so a handler
 * declaring `ENQUEUE` yields `OPENED` or `QUEUED`, one declaring `ACCEPT` yields
 * `OPENED` or `JOINED`, and one declaring `REJECT` only ever yields `OPENED` (a
 * mid-turn arrival never gets admitted, so it has no disposition at all).
 *
 * Reported in two places for two audiences: on `AgentMessageReply.disposition`, so the
 * SENDER learns what became of its own message, and on the `message_accepted` event, so
 * every OBSERVER of the stream learns the same thing.
 */
export type MessageDisposition = "opened" | "joined" | "queued";

/**
 * Transport envelope for one stream event.
 *
 * The single concrete type published on — and subscribed to from — the
 * `turn_events` topic. Composes over a `AgentStreamItem` payload
 * (`event`) and adds the routing metadata the harness stamps at publish time.
 * Producers never build this — they construct a payload and the publisher wraps
 * it — so `agent_id` / `turn_id` / `turn_number` / `message_id` / `timestamp`
 * can only ever be set by the harness. Being a concrete type (not a bare union), it is
 * also a clean `type` for the workflow-stream topic and subscribe `result_type`.
 */
export interface AgentEvent {
  /**
   * The short, TREE-UNIQUE id of the agent that PUBLISHED this event (`AgentConfig.agent_id` / `AgentStatus.agent_id` — see `AgentId` for the segment shape; NOT the full workflow_id) — stamped by the harness at publish time; producers never set it. Every event carries it so a merged multi-agent stream is self-describing: because the id is unique across the whole subagent tree, a consumer can filter to one agent's events, or group the merged stream by agent, with no risk of conflating two agents. For a subagent it equals the `handle` its parent references it by (the parent's own id plus a fresh segment, pushed down as the child's `agent_id`), so a consumer can attribute child events to the subagent shown in the parent's status/events.
   */
  agent_id: string;
  /**
   * The id of the turn this event belongs to — stamped by the harness at publish time; producers never set it.
   */
  turn_id: string;
  /**
   * The monotonic number of the turn this event belongs to — stamped by the harness at publish time; producers never set it.
   */
  turn_number: number;
  /**
   * The id of the ONE inbound message whose dispatch produced this event — minted at admission (also returned on `AgentMessageReply.message_id`) and stamped by the harness; producers never set it. It lives on the envelope rather than in event bodies so EVERY event of a message's dispatch is attributable for free — deltas, tool lifecycle, approvals, subagent brackets — exactly the way `turn_id` is.
   *
   * `turn_id` does NOT substitute for it: a turn is refcounted, so a `MidTurn.ACCEPT` message can join one already open and several messages then publish under one `turn_id`. Pair a reply, or attribute a streamed delta, by THIS field.
   *
   * `None` for events that genuinely are not about one message: `turn_started` and `turn_end` (pure turn lifecycle), and the approval/callback resolutions published from an update handler driving a policy cascade — which is no more bound to one message than it is to one turn.
   */
  message_id: string | null;
  /**
   * When the harness published this envelope (epoch seconds).
   */
  timestamp: number;
  /**
   * The wrapped stream-event payload — a discriminated union over `type` that Temporal's Pydantic converter reconstructs to the concrete payload subtype on read.
   */
  event:
    | MessageAccepted
    | MessageHandlerStart
    | MessageHandlerEnd
    | MessageHandlerError
    | TurnStarted
    | TurnEnded
    | ModelInteractionStarted
    | ModelInteractionEnded
    | ToolRequested
    | ToolApprovalRequested
    | AutoApprovalEvaluationStarted
    | AutoApprovalEvaluationEnded
    | AutoApprovalEvaluationSuperseded
    | AutoApprovalEvaluationError
    | ToolApprovalResolved
    | ToolStartEvent
    | ToolEndEvent
    | ToolProgressDelta
    | ToolErrorEvent
    | CallbackRequested
    | CallbackResolved
    | SubagentStarted
    | SubagentStopped
    | SubagentMessageSent
    | SubagentReplyReceived
    | SubagentStreamUnavailable
    | ReplyDelta
    | ThoughtSummaryDelta
    | TextAnnotationDelta
    | AgentStateSnapshot
    | AgentStatePatch;
}
/**
 * What one committed `mutate()` block changed, as RFC 6902 ops.
 *
 * The harness derives these; nothing in the author's workflow code builds or sees
 * them. Ops are applied in order, and a version is produced only by a block that
 * actually touched something — a no-op `mutate()` publishes nothing at all.
 */
export interface AgentStatePatch {
  type: "state_patch";
  /**
   * Which registered state these ops apply to.
   */
  state_id: string;
  /**
   * The version this patch produces.
   */
  version: number;
  /**
   * RFC 6902 operations, applied in order to the `version - 1` document. The harness only ever emits `add` / `replace` / `remove`.
   */
  ops: {
    [k: string]: unknown | undefined;
  }[];
}
/**
 * The full value of one piece of observable agent state.
 *
 * Published when the author registers the state, and again on nothing else — the
 * `version` here is the base every subsequent `AgentStatePatch` for the
 * same `state_id` builds on.
 */
export interface AgentStateSnapshot {
  type: "state_snapshot";
  /**
   * The name the workflow author registered this state under. Unique per agent; a consumer keys its local copy by it.
   */
  state_id: string;
  /**
   * The state's version at the moment of the snapshot. Patches carry strictly increasing versions from here.
   */
  version: number;
  /**
   * The whole state, as `model_dump(mode='json')` — the same serialization the patch ops' values use, so pointers line up.
   */
  value: {
    [k: string]: unknown | undefined;
  };
}
/**
 * An automatic approval evaluator returned a verdict, closing its bracket.
 */
export interface AutoApprovalEvaluationEnded {
  type: "auto_approval_evaluation_ended";
  /**
   * Stable correlation id chosen once when the call is requested and echoed by every later event of the SAME tool invocation (requested → start → progress → end/error).
   */
  tool_id: string;
  /**
   * The name of the invoked tool. Cannot ALONE disambiguate two parallel calls to the same tool, hence the separate tool_id.
   */
  tool_name: string;
  /**
   * Correlates this evaluation's started event with its ended/error event. `tool_id` is NOT enough: an agent may chain several evaluators over one gated call (a cheap check, then an expensive one), and two evaluations of the same call would be indistinguishable without this.
   */
  evaluation_id: string;
  /**
   * What is doing the judging — `jev_evaluator` for the builtin AI approver, otherwise the evaluator callable's qualified name. Read off the CALLABLE (its `__auto_mode_evaluator__` attribute) rather than off a returned decision, so the started event and the error event can both name it — neither has a decision to read it from.
   */
  evaluator: string;
  /**
   * What the evaluator SAID — approve, deny, or escalate to a human. This is the evaluator's answer, not necessarily the call's outcome: see `applied`.
   */
  verdict: AutoApprovalVerdict;
  /**
   * The evaluator's one-line summary. On an approve or deny this is also the reason published on the resulting ToolApprovalResolved (and, on a deny, the error the model receives); on an escalate this event is the ONLY place it appears, because an escalate resolves nothing.
   */
  reason: string | null;
  /**
   * The evaluator's own structured reasoning, free-form by design so an evaluator can record whatever makes its decision reviewable. The builtin Jev approver records the model id and request id, the verdict's confidence and full probability distribution, the irreversibility judgment, token usage, and the thresholds applied — the thresholds being what lets a stored decision be replayed against different ones without re-running inference. Empty when the evaluator recorded none.
   */
  details: {
    [k: string]: unknown | undefined;
  };
}
/**
 * An automatic approval evaluator raised instead of returning a verdict.
 */
export interface AutoApprovalEvaluationError {
  type: "auto_approval_evaluation_error";
  /**
   * Stable correlation id chosen once when the call is requested and echoed by every later event of the SAME tool invocation (requested → start → progress → end/error).
   */
  tool_id: string;
  /**
   * The name of the invoked tool. Cannot ALONE disambiguate two parallel calls to the same tool, hence the separate tool_id.
   */
  tool_name: string;
  /**
   * Correlates this evaluation's started event with its ended/error event. `tool_id` is NOT enough: an agent may chain several evaluators over one gated call (a cheap check, then an expensive one), and two evaluations of the same call would be indistinguishable without this.
   */
  evaluation_id: string;
  /**
   * What is doing the judging — `jev_evaluator` for the builtin AI approver, otherwise the evaluator callable's qualified name. Read off the CALLABLE (its `__auto_mode_evaluator__` attribute) rather than off a returned decision, so the started event and the error event can both name it — neither has a decision to read it from.
   */
  evaluator: string;
  /**
   * The failure, as text. The harness substitutes an escalate, so the call falls through to the human gate rather than being approved or failing the turn.
   */
  message: string;
}
/**
 * An automatic approval evaluator has begun judging a gated call.
 *
 * Deliberately carries no judgment: it is published before the evaluator is invoked, so
 * there is nothing for it to carry. Its value is the opening of the bracket — see
 * `AgentEventType.AUTO_APPROVAL_EVALUATION_STARTED`.
 */
export interface AutoApprovalEvaluationStarted {
  type: "auto_approval_evaluation_started";
  /**
   * Stable correlation id chosen once when the call is requested and echoed by every later event of the SAME tool invocation (requested → start → progress → end/error).
   */
  tool_id: string;
  /**
   * The name of the invoked tool. Cannot ALONE disambiguate two parallel calls to the same tool, hence the separate tool_id.
   */
  tool_name: string;
  /**
   * Correlates this evaluation's started event with its ended/error event. `tool_id` is NOT enough: an agent may chain several evaluators over one gated call (a cheap check, then an expensive one), and two evaluations of the same call would be indistinguishable without this.
   */
  evaluation_id: string;
  /**
   * What is doing the judging — `jev_evaluator` for the builtin AI approver, otherwise the evaluator callable's qualified name. Read off the CALLABLE (its `__auto_mode_evaluator__` attribute) rather than off a returned decision, so the started event and the error event can both name it — neither has a decision to read it from.
   */
  evaluator: string;
}
/**
 * An automatic approval evaluator was cancelled because its gate was settled first.
 */
export interface AutoApprovalEvaluationSuperseded {
  type: "auto_approval_evaluation_superseded";
  /**
   * Stable correlation id chosen once when the call is requested and echoed by every later event of the SAME tool invocation (requested → start → progress → end/error).
   */
  tool_id: string;
  /**
   * The name of the invoked tool. Cannot ALONE disambiguate two parallel calls to the same tool, hence the separate tool_id.
   */
  tool_name: string;
  /**
   * Correlates this evaluation's started event with its ended/error event. `tool_id` is NOT enough: an agent may chain several evaluators over one gated call (a cheap check, then an expensive one), and two evaluations of the same call would be indistinguishable without this.
   */
  evaluation_id: string;
  /**
   * What is doing the judging — `jev_evaluator` for the builtin AI approver, otherwise the evaluator callable's qualified name. Read off the CALLABLE (its `__auto_mode_evaluator__` attribute) rather than off a returned decision, so the started event and the error event can both name it — neither has a decision to read it from.
   */
  evaluator: string;
  /**
   * What the evaluator had concluded before it was cut off, in the narrow race where its answer arrived in the same workflow activation as the decision that beat it. Normally None: a cancelled evaluator never reaches a verdict.
   */
  verdict: AutoApprovalVerdict | null;
}
/**
 * A callback tool call is awaiting a result from an external client.
 *
 * Sits between `ToolStartEvent` and `ToolEndEvent` for the same call, sharing
 * their `tool_id` + `tool_name`. The tool has no worker-side body: an attached client
 * fulfills it on its own machine and returns the result via a `provide_callback_result`
 * update keyed on `tool_id`.
 */
export interface CallbackRequested {
  type: "callback_requested";
  /**
   * Stable correlation id chosen once when the call is requested and echoed by every later event of the SAME tool invocation (requested → start → progress → end/error).
   */
  tool_id: string;
  /**
   * The name of the invoked tool. Cannot ALONE disambiguate two parallel calls to the same tool, hence the separate tool_id.
   */
  tool_name: string;
  /**
   * The model-facing arguments of the callback call (injected parameters excluded), so the fulfilling client sees exactly what the model asked for.
   */
  tool_input: {
    [k: string]: unknown | undefined;
  };
  /**
   * JSON schema of the result the client must return — derived from the callback tool's declared output type. The client's result is validated against this before it resolves the call.
   */
  output_schema: {
    [k: string]: unknown | undefined;
  };
}
/**
 * A pending callback tool call was resolved — result returned, error, or timeout.
 */
export interface CallbackResolved {
  type: "callback_resolved";
  /**
   * Stable correlation id chosen once when the call is requested and echoed by every later event of the SAME tool invocation (requested → start → progress → end/error).
   */
  tool_id: string;
  /**
   * The name of the invoked tool. Cannot ALONE disambiguate two parallel calls to the same tool, hence the separate tool_id.
   */
  tool_name: string;
  /**
   * 'ok' if the client returned a result (validated against the tool's output type) — TOOL_END follows; 'error' if the client reported a failure fulfilling the call; 'timeout' if the wait elapsed (or the agent closed) before any result arrived. On 'error'/'timeout' the call fails and TOOL_ERROR follows.
   */
  outcome: "ok" | "error" | "timeout";
  /**
   * The client-reported failure message ('error'), the timeout/close note ('timeout'), or None on 'ok'.
   */
  error: string | null;
}
/**
 * One inbound message passed admission — what was sent, and what it did to the turn.
 *
 * The first event of a message's life, published from the synchronous admission prologue
 * of `send_agent_message`. It is the ONLY event carrying the message's content, which is
 * why it is standalone rather than folded into `TurnStarted`: a message that JOINS
 * an open turn starts no turn of its own, so there would be nothing to fold it into.
 */
export interface MessageAccepted {
  type: "message_accepted";
  /**
   * Which `@agent.accepts` handler the message is addressed to — the `AgentMessage.type` envelope field, named for what it actually is.
   */
  handler: string;
  /**
   * The message's payload as sent — the JSON of the handler's input model. Carried structurally rather than pre-rendered so a consumer can display it however it likes (and validate it against the handler's `parameters` schema).
   */
  payload: {
    [k: string]: unknown | undefined;
  };
  /**
   * What this message did to the agent's turn: OPENED a new one, JOINED the turn already open, or QUEUED behind it. The envelope's `turn_id` / `turn_number` name the turn in question — already running for JOINED, still to start for the other two.
   */
  disposition: MessageDisposition;
}
/**
 * One message's handler returned — its reply. Terminal for the MESSAGE.
 *
 * Not necessarily terminal for the turn: with several participants sharing a turn there is
 * one of these per message, all under the same `turn_id`, and `TurnEnded` follows
 * only the last. A consumer pairing a reply with the message that produced it MUST use the
 * envelope's `message_id`; `turn_id` no longer distinguishes them, and reply order is
 * not a workaround (nothing guarantees the turn's opening message replies last).
 */
export interface MessageHandlerEnd {
  type: "message_handler_end";
  /**
   * The handler's return model serialized to JSON (the harness publishes `result.model_dump(mode="json")`). Carrying a plain dict keeps the reply trivially round-trippable on the stream regardless of the concrete output type; a consumer that knows the expected type (e.g. from `agent_interface`) re-validates the dict into it.
   */
  output: {
    [k: string]: unknown | undefined;
  };
}
/**
 * One message's handler raised. Terminal for the MESSAGE, never for the session.
 *
 * The error half of the `MessageHandlerEnd` pair (exactly as `tool_error` is to
 * `tool_end`). It ends only this message: sibling participants of the same turn keep
 * running, and `TurnEnded` still follows once the last of them leaves. Attribute it
 * by the envelope's `message_id` — treating it as "the turn failed" would blame work that
 * is still in flight.
 */
export interface MessageHandlerError {
  type: "message_handler_error";
  /**
   * A description of the error the message's handler raised.
   */
  message: string;
}
/**
 * This message's `@agent.accepts` handler has begun running.
 *
 * Empty by design: everything about the message was already published on
 * `MessageAccepted`, and the envelope's `message_id` pairs the two. The gap
 * between them is the message's queue latency.
 */
export interface MessageHandlerStart {
  type: "message_handler_start";
}
/**
 * One streaming model call has ended, closing a MODEL_INTERACTION_STARTED.
 *
 * Published exactly once for each `ModelInteractionStarted`.
 */
export interface ModelInteractionEnded {
  type: "model_interaction_ended";
  /**
   * The model the call was issued against (the same id as on the matching ModelInteractionStarted), or None if the producer didn't report it.
   */
  model: string | null;
  /**
   * The call's TokenUsage when the provider reported it, or None if unavailable — e.g. the stream errored before completing.
   */
  usage: TokenUsage | null;
}
/**
 * One streaming model call has begun — opening a span of MODEL work.
 *
 * The envelope's `turn_id` / `turn_number` say which turn it belongs to; within a
 * turn there may be many.
 */
export interface ModelInteractionStarted {
  type: "model_interaction_started";
  /**
   * The model the call was issued against (the requested id), when the producer knows it — None otherwise.
   */
  model: string | null;
}
/**
 * An incremental text chunk of the agent's reply.
 */
export interface ReplyDelta {
  type: "reply_delta";
  /**
   * One incremental text chunk (word/token) of the agent's reply.
   */
  text: string;
}
/**
 * This agent dispatched one message (a turn) to a subagent it is driving.
 */
export interface SubagentMessageSent {
  type: "subagent_message_sent";
  /**
   * The short id of the SUBAGENT being messaged (matches its SubagentStarted, and the `agent_id` on that subagent's own events). Distinct from the envelope's `agent_id` (this parent agent).
   */
  subagent_id: string;
  /**
   * Which wired agent type the messaged subagent is.
   */
  agent_key: string;
  /**
   * The messaged subagent's real child workflow id — what a consumer uses to correlate this dispatch with the matching turn on the subagent's OWN event stream (mounted via SubagentStarted; subagent streams are never mirrored onto this one).
   */
  workflow_id: string;
  /**
   * The `@agent.accepts` handler this message is addressed to on the subagent (the send_agent_message envelope 'type' — which of the subagent's accepted messages it is).
   */
  handler: string;
  /**
   * The turn number ON THE SUBAGENT that this dispatch starts — distinct from the enclosing AgentEvent's `turn_number`, which is THIS agent's (the parent's) turn. Several dispatches in one parent turn share that envelope turn_number but get distinct subagent_turn values; pairs with the turn_number on the subagent's OWN stream events.
   */
  subagent_turn: number;
  /**
   * The offset in the SUBAGENT's OWN stream at which this turn's events begin (the child stream position the parent resumes consumption from for this turn). A client merging the parent + subagent streams positions the child cursor here the first time it mounts the child — so a merge that starts mid-session (resuming at a parent turn that is not the child's first) skips the child's pre-resume history, whose own message_sent markers are not on the merged stream and could otherwise never be ordered. Unrelated address space from the parent stream's offsets.
   */
  from_offset: number;
}
/**
 * This agent received a subagent's reply for one turn it dispatched.
 *
 * The CLOSE marker of the `[subagent_message_sent … subagent_reply_received]` bracket
 * (mirrors `SubagentMessageSent`'s correlation fields), published in-workflow by the
 * parent's `run_subagent_turn` once the activity returns and the agent (workflow) actually
 * holds the reply — for EVERY accepted child turn (`outcome` distinguishes success from an
 * accepted-but-errored turn, which still emitted its own `turn_end`), but never for a
 * pre-acceptance rejection. Carries no reply payload (that rides the child's own
 * `message_handler_end` event + the send-tool's `tool_end`); it is a thin
 * close/correlation signal a stream-merge uses to order a subagent's whole turn ahead of
 * the parent observing its reply.
 */
export interface SubagentReplyReceived {
  type: "subagent_reply_received";
  /**
   * The short id of the SUBAGENT that replied (matches its SubagentMessageSent, and the `agent_id` on that subagent's own events). Distinct from the envelope's `agent_id` (this parent agent).
   */
  subagent_id: string;
  /**
   * Which wired agent type the replying subagent is.
   */
  agent_key: string;
  /**
   * The replying subagent's real child workflow id (matches the opening SubagentMessageSent) — the close-gate key a stream-merge correlates against.
   */
  workflow_id: string;
  /**
   * The handler this reply answers (the same send_agent_message envelope 'type' as the opening SubagentMessageSent).
   */
  handler: string;
  /**
   * The turn number ON THE SUBAGENT this reply closes — pairs with the opening SubagentMessageSent's subagent_turn, NOT the enclosing envelope's (parent's) turn_number.
   */
  subagent_turn: number;
  /**
   * 'ok' if the child turn produced a reply; 'error' if it was accepted but then errored / produced no reply (it still emitted its own turn_end, so the bracket closes either way). Never published for a pre-acceptance rejection.
   */
  outcome: "ok" | "error";
}
/**
 * This agent started a subagent (a child agent it drives).
 */
export interface SubagentStarted {
  type: "subagent_started";
  /**
   * The short id of the SUBAGENT this event is about — the id the parent references it by AND the `agent_id` the subagent stamps on its own events (the parent pushes it down as the child's id). Distinct from the enclosing envelope's `agent_id`, which is THIS (the parent) agent.
   */
  subagent_id: string;
  /**
   * Which wired agent type this subagent is.
   */
  agent_key: string;
  /**
   * The subagent's real child workflow id — what a consumer uses to dynamically mount the subagent's OWN event stream for a consolidated view (subagent streams are never mirrored onto this one).
   */
  workflow_id: string;
}
/**
 * This agent stopped a subagent it was driving (signalled `close` + dropped it).
 */
export interface SubagentStopped {
  type: "subagent_stopped";
  /**
   * The short id of the stopped SUBAGENT (matches the prior SubagentStarted). Distinct from the envelope's `agent_id` (this parent agent).
   */
  subagent_id: string;
  /**
   * Which wired agent type the stopped subagent was.
   */
  agent_key: string;
  /**
   * The stopped subagent's real child workflow id — what a consumer uses to unmount the subagent's event stream (matches the prior SubagentStarted).
   */
  workflow_id: string;
}
/**
 * The stream merge gave up obtaining a subagent's events; its DETAIL is degraded (non-fatal).
 *
 * SYNTHESIZED CLIENT-SIDE by the merge (never workflow-published) and injected into the merged
 * logical stream when a mounted subagent stream is unreadable/stalled. The merge stamps the
 * enclosing `AgentEvent`'s `agent_id` with this same `subagent_id` — so a UI that
 * groups events by `agent_id` routes this straight to the affected subagent's view, and a
 * root-only consumer (which filters to the root `agent_id`) ignores it. The parent stream is
 * unaffected; only the subagent's own turn detail is missing. No retry — a fresh attach recovers.
 */
export interface SubagentStreamUnavailable {
  type: "subagent_stream_unavailable";
  /**
   * The short id of the subagent whose events couldn't be obtained (matches the `subagent_id` on the parent's SubagentStarted/SubagentMessageSent, and the `agent_id` that subagent stamps on its own events).
   */
  subagent_id: string;
  /**
   * The subagent's real child workflow id (the stream the merge couldn't read).
   */
  workflow_id: string;
  /**
   * A short, human-facing note on why the subagent's events were unavailable (e.g. the child workflow has completed and its stream isn't yet replayable).
   */
  reason: string;
}
/**
 * A streamed annotation/citation delta interleaved with reply text.
 */
export interface TextAnnotationDelta {
  type: "text_annotation";
  /**
   * The raw `DeltaTextAnnotationDelta` payload dumped to a dict so consumers can position citations next to the surrounding `ReplyDelta` chunks.
   */
  delta: {
    [k: string]: unknown | undefined;
  };
}
/**
 * A streamed thought-summary chunk from the model.
 */
export interface ThoughtSummaryDelta {
  type: "thought_summary";
  /**
   * The raw `DeltaThoughtSummary` payload dumped to a dict.
   */
  delta: {
    [k: string]: unknown | undefined;
  };
}
/**
 * Provider-agnostic token accounting for one model interaction.
 *
 * A neutral summary the harness understands without knowing any model SDK — a
 * producer (e.g. the Gemini plugin) maps its own usage shape onto these fields. Every
 * field is optional: a provider that doesn't report a given count, or an interaction
 * that ends before usage is known, simply leaves it `None`. `total_tokens` is the
 * provider's own grand total when given (not necessarily the sum of the parts, since
 * providers count cached/tool-use tokens differently).
 *
 * Every field is optional: a provider that doesn't report a given count, or an
 * interaction that ends before usage is known, simply leaves it `None`.
 */
export interface TokenUsage {
  /**
   * Tokens in the prompt/input to the model, or None if unreported.
   */
  input_tokens: number | null;
  /**
   * Tokens the model generated as output, or None if unreported.
   */
  output_tokens: number | null;
  /**
   * Tokens spent on the model's reasoning/thinking, or None if unreported.
   */
  thought_tokens: number | null;
  /**
   * Input tokens served from the provider's prompt cache, or None if unreported.
   */
  cached_tokens: number | null;
  /**
   * Tokens attributed to tool use, or None if unreported.
   */
  tool_use_tokens: number | null;
  /**
   * The provider's own grand total when given (not necessarily the sum of the parts, since providers count cached/tool-use tokens differently), or None if unreported.
   */
  total_tokens: number | null;
}
/**
 * A gated tool call is awaiting a human approval decision.
 *
 * Sits between `ToolRequested` and `ToolStartEvent`, sharing their
 * `tool_id` + `tool_name`.
 */
export interface ToolApprovalRequested {
  type: "tool_approval_requested";
  /**
   * Stable correlation id chosen once when the call is requested and echoed by every later event of the SAME tool invocation (requested → start → progress → end/error).
   */
  tool_id: string;
  /**
   * The name of the invoked tool. Cannot ALONE disambiguate two parallel calls to the same tool, hence the separate tool_id.
   */
  tool_name: string;
  /**
   * The model-facing arguments of the gated call (injected parameters are excluded — they are not the model's choice) so an approver sees exactly what the model asked for.
   */
  tool_input: {
    [k: string]: unknown | undefined;
  };
}
/**
 * A pending tool approval was resolved — approved or denied.
 */
export interface ToolApprovalResolved {
  type: "tool_approval_resolved";
  /**
   * Stable correlation id chosen once when the call is requested and echoed by every later event of the SAME tool invocation (requested → start → progress → end/error).
   */
  tool_id: string;
  /**
   * The name of the invoked tool. Cannot ALONE disambiguate two parallel calls to the same tool, hence the separate tool_id.
   */
  tool_name: string;
  /**
   * True if the call is approved (it will now execute), False if denied (it ends here without ever executing and the model receives an error result).
   */
  approved: boolean;
  /**
   * An optional human-supplied note, also set to the auto-denial reason when the agent closes while the approval is still pending.
   */
  reason: string | null;
  /**
   * Whether THIS decision asked to be remembered — i.e. an 'approve, and stop asking me about this tool' decision that allow-lists the tool on the live ToolApprovalPolicy. False for a one-off decision and for a call swept up by a policy change (e.g. the cascade that auto-approves other pending calls of a now-allow-listed tool, whose reason is the auto-approval note).
   */
  remember: boolean;
}
/**
 * A tool invocation has completed.
 */
export interface ToolEndEvent {
  type: "tool_end";
  /**
   * Stable correlation id chosen once when the call is requested and echoed by every later event of the SAME tool invocation (requested → start → progress → end/error).
   */
  tool_id: string;
  /**
   * The name of the invoked tool. Cannot ALONE disambiguate two parallel calls to the same tool, hence the separate tool_id.
   */
  tool_name: string;
  /**
   * The tool's final, single result payload.
   */
  tool_output: string;
}
/**
 * A tool invocation has failed.
 *
 * Terminal for that specific tool call — the UI can resolve the card out of its
 * "running" state. The turn itself may continue if the caller (e.g. Gemini AFC)
 * decides to retry or surface the failure back to the model.
 */
export interface ToolErrorEvent {
  type: "tool_error";
  /**
   * Stable correlation id chosen once when the call is requested and echoed by every later event of the SAME tool invocation (requested → start → progress → end/error).
   */
  tool_id: string;
  /**
   * The name of the invoked tool. Cannot ALONE disambiguate two parallel calls to the same tool, hence the separate tool_id.
   */
  tool_name: string;
  /**
   * A description of why the tool invocation failed.
   */
  message: string;
}
/**
 * An intermediate progress chunk emitted by a tool mid-execution.
 *
 * Distinct from `ToolEndEvent`'s final payload: this is for tools doing
 * genuine multi-step work (e.g. a custom tool that connects to a service,
 * issues several requests, then returns) that want to report progress as they
 * go. Whether a tool streams these is a property of the tool's semantics, not
 * of how a transport happens to chunk its output. No tool emits this yet; see
 * the producer note in `google_genai_plugin/_interactions_activity.py`.
 */
export interface ToolProgressDelta {
  type: "tool_progress_delta";
  /**
   * Stable correlation id chosen once when the call is requested and echoed by every later event of the SAME tool invocation (requested → start → progress → end/error).
   */
  tool_id: string;
  /**
   * The name of the invoked tool. Cannot ALONE disambiguate two parallel calls to the same tool, hence the separate tool_id.
   */
  tool_name: string;
  /**
   * One intermediate progress chunk emitted mid-execution, before the terminal TOOL_END payload.
   */
  progress_delta: string;
}
/**
 * The model has requested a tool call that has not begun executing yet.
 *
 * Precedes `ToolStartEvent` in the tool lifecycle (requested → start →
 * end/error). Carries the same `tool_id` + `tool_name` as the eventual start,
 * so a UI can render the pending call and a future approval policy can evaluate it
 * before it runs.
 */
export interface ToolRequested {
  type: "tool_requested";
  /**
   * Stable correlation id chosen once when the call is requested and echoed by every later event of the SAME tool invocation (requested → start → progress → end/error).
   */
  tool_id: string;
  /**
   * The name of the invoked tool. Cannot ALONE disambiguate two parallel calls to the same tool, hence the separate tool_id.
   */
  tool_name: string;
  /**
   * The full arguments of the requested call, so a UI can render the pending call and a future approval policy can evaluate it before it runs.
   */
  tool_input: {
    [k: string]: unknown | undefined;
  };
}
/**
 * A tool invocation has begun executing.
 */
export interface ToolStartEvent {
  type: "tool_start";
  /**
   * Stable correlation id chosen once when the call is requested and echoed by every later event of the SAME tool invocation (requested → start → progress → end/error).
   */
  tool_id: string;
  /**
   * The name of the invoked tool. Cannot ALONE disambiguate two parallel calls to the same tool, hence the separate tool_id.
   */
  tool_name: string;
  /**
   * The full arguments the tool began executing with.
   */
  tool_input: {
    [k: string]: unknown | undefined;
  };
}
/**
 * A turn has fully completed and the agent is idle, awaiting the next message.
 *
 * Closes the bracket opened by `TurnStarted`. Published for EVERY turn, when its
 * LAST participant leaves — after that participant's `MessageHandlerEnd` or
 * `MessageHandlerError` — so it is the agent's true quiescence signal and the
 * single reliable point a consumer can disconnect on. The envelope's `turn_id` /
 * `turn_number` identify which turn ended; its `message_id` is `None`, since the
 * turn belongs to no single message.
 */
export interface TurnEnded {
  type: "turn_end";
}
/**
 * A turn has begun — the agent went from idle to busy. A pure lifecycle bracket.
 *
 * Carries no message: a turn is the interval the agent is non-idle, not the span of one
 * message, and several messages can share it. The message that opened this turn is the
 * `MessageAccepted` published just before it with the same `turn_id`.
 */
export interface TurnStarted {
  type: "turn_started";
}

/** Every payload an `AgentEvent` can carry, discriminated by `type`. */
export type AgentStreamItem =
  | MessageAccepted
  | MessageHandlerStart
  | MessageHandlerEnd
  | MessageHandlerError
  | TurnStarted
  | TurnEnded
  | ModelInteractionStarted
  | ModelInteractionEnded
  | ToolRequested
  | ToolApprovalRequested
  | AutoApprovalEvaluationStarted
  | AutoApprovalEvaluationEnded
  | AutoApprovalEvaluationSuperseded
  | AutoApprovalEvaluationError
  | ToolApprovalResolved
  | ToolStartEvent
  | ToolEndEvent
  | ToolProgressDelta
  | ToolErrorEvent
  | CallbackRequested
  | CallbackResolved
  | SubagentStarted
  | SubagentStopped
  | SubagentMessageSent
  | SubagentReplyReceived
  | SubagentStreamUnavailable
  | ReplyDelta
  | ThoughtSummaryDelta
  | TextAnnotationDelta
  | AgentStateSnapshot
  | AgentStatePatch;

/** The `type` of every event on the stream. */
export type AgentEventType = AgentStreamItem["type"];
