// Code generated by nexus-rpc-gen. DO NOT EDIT.

package handler

import "github.com/nexus-rpc/sdk-go/nexus"

// Nexus service that exposes an agent session to external callers (e.g. the Slack
// connector). The connector calls sendAgentMessage to deliver user input and pollMessages
// to consume the agent's response stream.
var AgentService = struct {
	ServiceName                                                                                                                                                                                                                                                                                      string
	// Start or reuse an agent workflow session and deliver a message to a named @agent.accepts// handler. Mirrors AgentClient.send_message() — msgType is the handler name (e.g. 'ask',// 'slash'), payload is its JSON-encoded input model. Returns the turn output for polling// via pollMessages.
	SendAgentMessage                                                                                                                                                                                                                                                                                 nexus.OperationReference[SendAgentMessageInput, SendMessageOutput]
	// Execute a harness-level operator command (e.g. /approvals, /stop, /status). Does not// create a turn — the harness applies the change directly and returns a reply string// synchronously.                                                                                                    
	ExecuteOperatorCommand                                                                                                                                                                                                                                                                           nexus.OperationReference[ExecuteOperatorCommandInput, ExecuteOperatorCommandOutput]
	// Resolve a pending tool-approval gate. The workflow's tool_approval update records the// decision; the gated tool call proceeds (or is rejected) immediately.                                                                                                                                  
	ApproveToolCall                                                                                                                                                                                                                                                                                  nexus.OperationReference[ApproveToolCallInput, ApproveToolCallOutput]
	// Return the list of @agent.accepts handlers the agent exposes — name, description, and// input/output schemas — mirroring AgentClient.get_agent_interface(). Use this to construct// valid sendAgentMessage payloads or to model the agent as a subagent tool.                                 
	QueryAgentInterface                                                                                                                                                                                                                                                                              nexus.OperationReference[QuerySessionInput, AgentInterfaceOutput]
	// Return the list of operator commands the agent accepts. Use this to build the Slack App// manifest slash_commands section and to route incoming slash commands to the correct// operation.                                                                                                    
	QueryOperatorInterface                                                                                                                                                                                                                                                                           nexus.OperationReference[QuerySessionInput, QueryOperatorInterfaceOutput]
	// Return a snapshot of the agent session's current state: turn counter, whether a turn is// active, pending tool approvals, and message-queuing configuration. Mirrors// AgentClient.get_status().                                                                                              
	QueryAgentStatus                                                                                                                                                                                                                                                                                 nexus.OperationReference[QuerySessionInput, AgentStatusOutput]
	// Async operation — attaches a completion callback to WorkflowStream's built-in poll update// so reply_delta events published from the agent workflow are delivered. Returns a batch of// stream items (WorkflowStream PollResult wire format) plus the next cursor.                            
	PollMessages                                                                                                                                                                                                                                                                                     nexus.OperationReference[PollMessagesInput, PollMessagesOutput]
}{
	ServiceName:            "AgentService",
	SendAgentMessage:       nexus.NewOperationReference[SendAgentMessageInput, SendMessageOutput]("sendAgentMessage"),
	ExecuteOperatorCommand: nexus.NewOperationReference[ExecuteOperatorCommandInput, ExecuteOperatorCommandOutput]("executeOperatorCommand"),
	ApproveToolCall:        nexus.NewOperationReference[ApproveToolCallInput, ApproveToolCallOutput]("approveToolCall"),
	QueryAgentInterface:    nexus.NewOperationReference[QuerySessionInput, AgentInterfaceOutput]("queryAgentInterface"),
	QueryOperatorInterface: nexus.NewOperationReference[QuerySessionInput, QueryOperatorInterfaceOutput]("queryOperatorInterface"),
	QueryAgentStatus:       nexus.NewOperationReference[QuerySessionInput, AgentStatusOutput]("queryAgentStatus"),
	PollMessages:           nexus.NewOperationReference[PollMessagesInput, PollMessagesOutput]("pollMessages"),
}

type SendAgentMessageInput struct {
	// Target @agent.accepts handler name (e.g. 'ask', 'slash')                                        
	MsgType                                                                                     string `json:"msgType"`
	// JSON-encoded input matching the target handler's input model (e.g. '{"text":"hello"}' for       
	// the 'ask' handler)                                                                              
	Payload                                                                                     string `json:"payload"`
	// Provider-prefixed session identifier (e.g. slack:C12345)                                        
	SessionID                                                                                   string `json:"sessionId"`
}

type SendMessageOutput struct {
	// True if the message was queued behind an active turn rather than dispatched immediately       
	Pending                                                                                   bool   `json:"pending,omitempty"`
	// Stream log offset at message-accept time; start the first pollMessages call from this         
	// offset to skip prior-turn history                                                             
	StreamHeadOffset                                                                          int64  `json:"streamHeadOffset,omitempty"`
	// Unique ID for this turn                                                                       
	TurnID                                                                                    string `json:"turnId"`
	// Monotonic turn counter for this session                                                       
	TurnNumber                                                                                int64  `json:"turnNumber"`
}

type ExecuteOperatorCommandInput struct {
	// Optional argument string                                         
	Arg                                                          string `json:"arg,omitempty"`
	// Operator command name (e.g. 'approvals', 'stop', 'status')       
	Name                                                         string `json:"name"`
	// Provider-prefixed session identifier                             
	SessionID                                                    string `json:"sessionId"`
}

type ExecuteOperatorCommandOutput struct {
	// Human-readable reply text from the harness       
	Reply                                        string `json:"reply"`
}

type ApproveToolCallInput struct {
	// True to allow the tool call, false to deny it                                               
	Approved                                                                                bool   `json:"approved"`
	// Optional note surfaced on the resolution event and, on denial, fed back to the model        
	Reason                                                                                  string `json:"reason,omitempty"`
	// If true and approved, adds the tool to the session's auto-approve list so it won't be       
	// gated again                                                                                 
	Remember                                                                                bool   `json:"remember,omitempty"`
	// Provider-prefixed session identifier                                                        
	SessionID                                                                               string `json:"sessionId"`
	// The tool_id from the ToolApprovalRequested stream event                                     
	ToolID                                                                                  string `json:"toolId"`
}

type ApproveToolCallOutput struct {
	// Always true on success (the update validator rejects invalid decisions before the handler       
	// runs)                                                                                           
	Accepted                                                                                    bool   `json:"accepted"`
	// Echo of the resolved tool ID                                                                    
	ToolID                                                                                      string `json:"toolId"`
}

type QuerySessionInput struct {
	// Provider-prefixed session identifier       
	SessionID                              string `json:"sessionId"`
}

type AgentInterfaceOutput struct {
	// Ordered list of @agent.accepts handlers the agent exposes                 
	Handlers                                                    []HandlerElement `json:"handlers"`
}

// One @agent.accepts handler exposed by the agent, described tool-style (mirrors harness
// AcceptedFunction)
type HandlerElement struct {
	// Handler docstring describing when and how to use it                   
	Description                                                       string `json:"description"`
	// Handler name — the value to pass as msgType in sendAgentMessage       
	Name                                                              string `json:"name"`
	// JSON-encoded JSON Schema for the handler's return model               
	Output                                                            string `json:"output"`
	// JSON-encoded JSON Schema for the handler's input model                
	Parameters                                                        string `json:"parameters"`
}

type QueryOperatorInterfaceOutput struct {
	// Ordered list of operator commands the agent accepts                 
	Commands                                              []CommandElement `json:"commands"`
}

type CommandElement struct {
	Argument                                                             *Argument `json:"argument,omitempty"`
	// Human-readable description suitable for a Slack manifest entry              
	Description                                                          string    `json:"description"`
	// Display label including the slash (e.g. '/scope')                           
	Label                                                                string    `json:"label"`
	// Canonical command name used as the routing key (e.g. 'scope')               
	Name                                                                 string    `json:"name"`
	// 'harness' for built-in commands, 'agent' for agent-registered ones          
	Source                                                               string    `json:"source"`
}

// Argument metadata for rendering a UI hint or menu
type Argument struct {
	// Whether multiple space-separated values are accepted         
	AllowMultiple                                          bool     `json:"allowMultiple,omitempty"`
	// Valid choices when kind is 'enum'                            
	Choices                                                []string `json:"choices,omitempty"`
	// 'enum' | 'text' | 'tool_names'                               
	Kind                                                   string   `json:"kind"`
	// Hint text for the argument (e.g. 'docs|forum|all')           
	Placeholder                                            string   `json:"placeholder,omitempty"`
	// Whether the argument must be provided                        
	Required                                               bool     `json:"required"`
}

// Mirrors harness AgentStatus — the single source of truth for session state
type AgentStatusOutput struct {
	// This agent's own short ID (stamped on every event it publishes)                         
	AgentID                                                           string                   `json:"agentId"`
	// Monotonic turn counter                                                                  
	CurrentTurn                                                       int64                    `json:"currentTurn"`
	// True if the session accepts messages while a turn is active                             
	IsMessageQueuingEnabled                                           bool                     `json:"isMessageQueuingEnabled"`
	// Gated tool calls currently awaiting a human decision                                    
	PendingApprovals                                                  []PendingApprovalElement `json:"pendingApprovals"`
	// True if a turn is currently running                                                     
	TurnActive                                                        bool                     `json:"turnActive"`
}

// A gated tool call awaiting a human decision (mirrors harness PendingApproval)
type PendingApprovalElement struct {
	// ID to pass to approveToolCall                                             
	ToolID                                                                string `json:"toolId"`
	// JSON-encoded model-facing tool input (injected parameters excluded)       
	ToolInput                                                             string `json:"toolInput"`
	// Human-readable tool name                                                  
	ToolName                                                              string `json:"toolName"`
	// Turn that triggered this approval request                                 
	TurnNumber                                                            int64  `json:"turnNumber"`
}

type PollMessagesInput struct {
	Cursor                                                                                int64   `json:"cursor"`
	// Provider-prefixed session identifier                                                       
	SessionID                                                                             string  `json:"sessionId"`
	// How long the WorkflowStream poll update waits for new events before returning empty        
	TimeoutSeconds                                                                        float64 `json:"timeoutSeconds,omitempty"`
}

// Mirrors WorkflowStream PollResult wire format so the async update-with-callback payload
// decodes correctly without transformation.
type PollMessagesOutput struct {
	// True only in the sync error path when the agent workflow has already completed              
	Closed                                                                           bool          `json:"closed,omitempty"`
	// Stream events since cursor; decode each as TurnEvent and map to Slack output                
	Items                                                                            []ItemElement `json:"items"`
	// True when more items are immediately available (batch was capped)                           
	MoreReady                                                                        bool          `json:"more_ready"`
	// Next cursor value to use in the following pollMessages call                                 
	NextOffset                                                                       int64         `json:"next_offset"`
}

// One event from WorkflowStream._log. Data is base64(proto Payload{encoding:json/plain,
// data:TurnEvent JSON}).
type ItemElement struct {
	// base64-encoded proto Payload containing a TurnEvent       
	Data                                                  string `json:"data"`
	// Absolute position of this item in the stream              
	Offset                                                int64  `json:"offset"`
	// Stream topic name (turn_events)                           
	Topic                                                 string `json:"topic"`
}
