// TypeScript types for one agent, from the document `temporal-agent-harness schema` prints:
// an interface per model in its `$defs`, plus one mapping type naming every handler's input
// and output and every declared state.

import { compile, type JSONSchema } from "json-schema-to-typescript";

/** The document `temporal-agent-harness schema module:Class` prints. */
export interface AgentSchemaDocument {
  agent: string;
  source: string;
  handlers: Record<
    string,
    { description: string; mid_turn: string; input: SchemaRef; output: SchemaRef }
  >;
  states: Record<string, SchemaRef>;
  $defs: Record<string, JSONSchema>;
}

interface SchemaRef {
  $ref: string;
}

export interface GenerateOptions {
  /** Name of the mapping type. Defaults to the agent's workflow type name. */
  typeName?: string;
}

const REF_PREFIX = "#/$defs/";
const ROOT = "HarnessCodegenRoot";

// Constraints json-schema-to-typescript drops, carried into the JSDoc instead.
const CONSTRAINT_KEYWORDS = [
  "minimum",
  "maximum",
  "exclusiveMinimum",
  "exclusiveMaximum",
  "minLength",
  "maxLength",
  "pattern",
  "minItems",
  "maxItems"
] as const;

// Keywords whose values are data rather than schemas, so they are copied as they are.
const DATA_KEYWORDS = new Set(["default", "examples", "const", "enum"]);

export async function generateAgentTypes(
  doc: AgentSchemaDocument,
  options: GenerateOptions = {}
): Promise<string> {
  const names = typeNames(Object.keys(doc.$defs));
  const typeName = options.typeName ?? safeName(doc.agent);
  if ([...names.values()].includes(typeName)) {
    throw new Error(
      `the mapping type name ${typeName} is also the name of one of the agent's models; ` +
        "pass a different name"
    );
  }

  const defs: Record<string, JSONSchema> = {};
  for (const [key, schema] of Object.entries(doc.$defs)) {
    defs[key] = { ...(prepare(schema) as JSONSchema), title: names.get(key)! };
  }
  const root: JSONSchema = {
    title: ROOT,
    anyOf: Object.keys(defs).map((key) => ({ $ref: `${REF_PREFIX}${key}` })),
    $defs: defs
  };
  const models = await compile(root, ROOT, {
    bannerComment: "",
    additionalProperties: false,
    unknownAny: true,
    strictIndexSignatures: true
  });

  return [
    `// GENERATED by @temporal-agent-harness/codegen from ${doc.source}. Do not edit.`,
    "",
    dropRoot(models).trim(),
    "",
    mappingType(doc, typeName, names),
    ""
  ].join("\n");
}

/** Remove property-level titles (json-schema-to-typescript would turn each into its own named
 *  type) and fold constraints into the description. */
function prepare(node: unknown): unknown {
  if (Array.isArray(node)) return node.map(prepare);
  if (node === null || typeof node !== "object") return node;

  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(node)) {
    if (key === "title") continue;
    if (DATA_KEYWORDS.has(key)) out[key] = value;
    else if (key === "properties" || key === "$defs" || key === "patternProperties")
      out[key] = Object.fromEntries(
        Object.entries(value as Record<string, unknown>).map(([k, v]) => [k, prepare(v)])
      );
    else out[key] = prepare(value);
  }

  const tags = CONSTRAINT_KEYWORDS.filter((k) => k in out).map(
    (k) => `@${k} ${String(out[k])}`
  );
  if (tags.length > 0) {
    const description = typeof out.description === "string" ? `${out.description}\n\n` : "";
    out.description = description + tags.join("\n");
  }
  return out;
}

function mappingType(
  doc: AgentSchemaDocument,
  typeName: string,
  names: Map<string, string>
): string {
  const resolve = (ref: SchemaRef): string => {
    const key = ref.$ref.startsWith(REF_PREFIX) ? ref.$ref.slice(REF_PREFIX.length) : undefined;
    const name = key === undefined ? undefined : names.get(key);
    if (name === undefined) throw new Error(`unresolvable $ref ${ref.$ref}`);
    return name;
  };

  const handlers = Object.entries(doc.handlers).map(
    ([name, h]) =>
      `${jsdoc(h.description, "    ")}    ${name}: { input: ${resolve(h.input)}; output: ${resolve(h.output)} };`
  );
  const states = Object.entries(doc.states).map(
    ([id, ref]) => `    ${id}: ${resolve(ref)};`
  );
  const block = (lines: string[]) =>
    lines.length === 0 ? "Record<never, never>" : `{\n${lines.join("\n")}\n  }`;

  return [
    `/** The \`${doc.agent}\` agent's handlers (message in, reply out) and observable state. */`,
    `export interface ${typeName} {`,
    `  handlers: ${block(handlers)};`,
    `  states: ${block(states)};`,
    "}"
  ].join("\n");
}

function jsdoc(text: string, indent: string): string {
  const lines = text.trim().replaceAll("*/", "*\\/").split("\n");
  if (lines.length === 0 || lines[0] === "") return "";
  if (lines.length === 1) return `${indent}/** ${lines[0]} */\n`;
  return `${indent}/**\n${lines.map((l) => `${indent} * ${l}`.trimEnd()).join("\n")}\n${indent} */\n`;
}

/** The generated name for every `$defs` key, rejecting two keys that would share one. */
function typeNames(keys: string[]): Map<string, string> {
  const names = new Map<string, string>();
  const owners = new Map<string, string>();
  for (const key of keys) {
    const name = safeName(key);
    const other = owners.get(name);
    if (other !== undefined) {
      throw new Error(`models ${other} and ${key} would both be generated as ${name}`);
    }
    owners.set(name, key);
    names.set(key, name);
  }
  return names;
}

/** A TypeScript identifier for a schema name: `Echo-Input` → `EchoInput`. Already-safe
 *  PascalCase names come back unchanged, which json-schema-to-typescript also leaves alone. */
function safeName(raw: string): string {
  const name = raw
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0]!.toUpperCase() + part.slice(1))
    .join("");
  if (!/^[A-Za-z]/.test(name)) throw new Error(`cannot derive a type name from ${raw}`);
  return name;
}

function dropRoot(source: string): string {
  const start = source.indexOf(`export type ${ROOT} =`);
  if (start === -1) return source;
  const end = source.indexOf(";\n", start);
  return source.slice(0, start) + source.slice(end + 2);
}
