# Generated by nexus-rpc-gen. DO NOT EDIT!

from __future__ import annotations

from pydantic import BaseModel
from typing import Optional, List, Dict, Any
from nexusrpc import service, Operation


class RegisterNexusInput(BaseModel):
    """Input for registering a 1st-party Nexus service."""

    endpoint: Optional[str] = None
    """Temporal Nexus endpoint the service handlers are registered on."""

    name: Optional[str] = None
    """Service name prefix, e.g. "docsproxy"."""

    tools: Optional[List[Dict[str, Any]]] = None
    """Serialised mcp.types.Tool dicts with prefixed names."""


class RegisterExternalInput(BaseModel):
    """Input for registering a 3rd-party external MCP server."""

    name: Optional[str] = None
    """Service name prefix for the external server."""

    url: Optional[str] = None
    """Streamable-HTTP MCP endpoint URL."""


class DeregisterInput(BaseModel):
    """Input for removing a service registration."""

    name: Optional[str] = None
    """Service name to remove."""


@service
class RegistryService:
    """Cross-namespace gateway for registering and deregistering MCP services. Service workers
    in any Temporal namespace call these operations to register with the gateway's
    ToolRegistryWorkflow — a Nexus call rather than a direct workflow signal so it works
    across namespace boundaries.
    
    """
    register_nexus: Operation[RegisterNexusInput, None]
    """Register a 1st-party Nexus service with the gateway."""

    register_external: Operation[RegisterExternalInput, None]
    """Register a 3rd-party external MCP server with the gateway."""

    deregister: Operation[DeregisterInput, None]
    """Remove a service registration from the gateway."""
