// GENERATED by @temporal-agent-harness/codegen from examples.tictactoe.workflow:TicTacToeAgentWorkflow. Do not edit.

/**
 * The whole game: nine cells, whose turn it is, who the agent is, and the outcome.
 */
export interface Board {
  cells: (("X" | "O") | null)[];
  to_move: "X" | "O";
  agent_mark: "X" | "O";
  status: "playing" | "X_wins" | "O_wins" | "draw";
  moves: Move[];
}
/**
 * One move that has been played, in order.
 */
export interface Move {
  mark: "X" | "O";
  /**
   * 1-9, left-to-right, top-to-bottom.
   */
  cell: number;
}
/**
 * Start a fresh game.
 */
export interface NewGame {
  /**
   * If true the agent plays X and opens; otherwise you are X and open.
   */
  agent_goes_first?: boolean;
}
/**
 * Your move: the number of an empty cell.
 */
export interface PlayMove {
  /**
   * 1-9, reading left-to-right, top-to-bottom.
   *
   * @minimum 1
   * @maximum 9
   */
  cell: number;
}
/**
 * A free-form natural-language reply (the output of a plain chat handler).
 */
export interface TextReply {
  text: string;
}

/** The `TicTacToeAgent` agent's handlers (message in, reply out) and observable state. */
export interface TicTacToeAgent {
  handlers: {
    /**
     * Reset the board and start a new game. You are X and open unless
     * `agent_goes_first` is set, in which case the agent plays X and opens.
     */
    new_game: { input: NewGame; output: TextReply };
    /**
     * Play your mark on an empty cell (1-9, left-to-right, top-to-bottom). The agent
     * then judges the position with TypeSafe and answers with its own move.
     */
    play: { input: PlayMove; output: TextReply };
  };
  states: {
    board: Board;
  };
}
