# Generated by nexus-rpc-gen. DO NOT EDIT!

from __future__ import annotations

from pydantic import BaseModel
from typing import Optional, List, Dict, Any
from nexusrpc import service, Operation


class RegisterExternalInput(BaseModel):
    """Input for registering a 3rd-party external MCP server."""

    name: Optional[str] = None
    """Service name prefix for the external server."""

    url: Optional[str] = None
    """Streamable-HTTP MCP endpoint URL."""


class DeregisterInput(BaseModel):
    """Input for removing a service registration."""

    name: Optional[str] = None
    """Service name to remove."""


class ListToolsOutput(BaseModel):
    """All tool dicts for 3rd-party MCP servers currently registered with the gateway."""

    tools: Optional[List[Dict[str, Any]]] = None
    """Serialised mcp.types.Tool dicts."""


class CallToolInput(BaseModel):
    """Input for invoking one tool on a registered 3rd-party MCP server."""

    arguments: Optional[Dict[str, Any]] = None
    """Tool call arguments, as MCP's tools/call would pass them."""

    name: Optional[str] = None
    """Full prefixed tool name, e.g. "weather_get_forecast"."""


class CallToolOutput(BaseModel):
    """The tool's result, already flattened to text. Errors surface as a raised Nexus operation
    failure rather than a field on this type — callers catch exceptions the same way they
    already do for direct Nexus-native tool calls.
    """
    result: Optional[str] = None
    """The tool call's result, flattened to text."""


@service
class RegistryService:
    """The Durable Tools Gateway's Nexus surface. Its sole purpose is registering 3rd-party
    (non-Nexus) MCP servers and invoking their tools, durably, on the caller's behalf —
    Nexus-native MCP servers register and are called directly, bypassing this service
    entirely. Service workers in any Temporal namespace call these operations to reach the
    gateway's ToolRegistryWorkflow — a Nexus call rather than a direct workflow signal/query
    so it works across namespace boundaries.
    """
    register_external: Operation[RegisterExternalInput, None]
    """Register a 3rd-party external MCP server with the gateway."""

    deregister: Operation[DeregisterInput, None]
    """Remove a service registration from the gateway."""

    list_tools: Operation[None, ListToolsOutput]
    """Return all tool dicts for 3rd-party MCP servers currently registered with the gateway.
    Part of the shared MCP-over-Nexus list_tools contract (see
    authoring.MCPOverNexusService) so callers can treat the gateway uniformly alongside
    any Nexus-native MCP server.
    
    """

    call_tool: Operation[CallToolInput, CallToolOutput]
    """Invoke one tool on a 3rd-party MCP server registered with the gateway, dispatched via
    ToolCallWorkflow (a plain workflow wrapping one activity) — see
    ``registry_service_handler.py``'s ``call_tool`` docstring.
    """
